# Run this docker compose file if you want local versions
# of the database running on your machine using the follwing
# commands in this directory
#
# `docker volume create --name quotes_db`
# `docker compose up -d`

name: quotable

services:
  # For GUI, comment this section out when building and run npm run dev in /frontend/src/main/frontend to debug changes.
  frontend:
    build: ./frontend/src/main/frontend
    ports:
      - 9080:80

  quotes-service:
    build: ./_backend/services/quote-service
    ports:
      - 9082:9082
    environment:
      CONNECTION_STRING: "mongodb://user:password@quotes-database:27017/?directConnection=true"
    depends_on:
      - quotes-database

  user-service:
    build: ./_backend/services/user-service
    ports:
      - 9081:9081
    environment:
      CONNECTION_STRING: "mongodb://user:password@quotes-database:27017/?directConnection=true"
    depends_on:
      - quotes-database

  quotes-database:
    hostname: quotes-database
    image: mongodb/mongodb-atlas-local
    restart: always
    volumes:
      - data:/data/db
      - config:/data/configdb
    ports:
      - 27017:27017
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=user
      - MONGODB_INITDB_ROOT_PASSWORD=password

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "9083:80"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - user-service
      - quotes-service
volumes:
  data:
  config:
