name: Continuous Integration

on:
  push:
    branches: [ "main", "Testing" ]
  pull_request:
    branches: [ "main", "Testing" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker images
        run: docker compose build

      - name: Run tests
        working-directory: ./_backend/services/user-service
        run: mvn test
